update register and login view
tu-graz-library/invenio-theme-tugraz pull request #247
Opened 2021-10-19 16:15 UTC by rekt-hard

fix: remove redundant closing div tag for register
ui: add accordion for better overview

closes #245 
closes #246 

### Login View:
![Screenshot from 2021-10-19 16-54-16](https://user-images.githubusercontent.com/72449192/137950356-fe8a9003-dd47-4cee-9ff5-07e231442238.png)
![Screenshot from 2021-10-19 16-54-57](https://user-images.githubusercontent.com/72449192/137950360-f2833d7a-6a46-425b-9b7b-6706be4e76ba.png)

### Sign Up View:
![Screenshot from 2021-10-19 16-54-38](https://user-images.githubusercontent.com/72449192/137950178-807dd5c0-f19d-424c-bb60-f68272629411.png)
![Screenshot from 2021-10-19 16-55-13](https://user-images.githubusercontent.com/72449192/137950305-82b6542e-ed19-479d-8f1e-ce49fdfd44d9.png)

2021-10-20 07:34 UTC, mb-wali requested changes
looks good.

* could you please add a screenshot - to see how the signup page would look like when the signup option is disabled.
* extract and add the german translation for the new text - `Repository Credentials`

2021-10-20 07:34 UTC, mb-wali commented on invenio_theme_tugraz/templates/invenio_theme_tugraz/accounts/login_user.html
> +            <div style="padding-bottom: 20px;padding-top: 6px;">
we could remove the inline css and use a class instead.

2021-11-02 15:46 UTC, mb-wali commented on invenio_theme_tugraz/translations/de/LC_MESSAGES/messages.po
>  msgstr "Einloggen mit"
```suggestion
msgstr "Einloggen mit %(title)s"
```

2021-11-02 15:54 UTC, utnapischtim commented on invenio_theme_tugraz/translations/de/LC_MESSAGES/messages.po
> +msgstr "Einloggen mit Repository Daten"
Suggestion: Loggen Sie sich mit ihrem Repository-Account ein

2021-11-08 09:24 UTC, mb-wali approved these changes

2021-11-08 09:33 UTC, merged